name: Build and Deploy #这个 workflow 的名称，自己随便取
on: #触发条件
    push:
        branches:
            - main
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest # 运行所需要的虚拟机环境
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install and Build
              run: |
                  npm install
                  npm run docs:build

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@4.4.1

              with:
                  BRANCH: gh-pages
                  FOLDER: docs/.vitepress/dist
                  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
